[package]
name = "zerocbor"
description = "A zero-copy, zero-dependency, no_std-compatible, extremely fast CBOR (RFC 8949) serializer for Rust."
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
documentation = "https://docs.rs/zerocbor"
keywords = ["cbor", "rfc8949", "serialization", "no-std", "zero-copy"]
categories = ["encoding", "no-std", "parsing"]

[features]
default = ["std"]
std = []
derive = ["dep:zerocbor_derive"]
f16 = []

[dependencies]
zerocbor_derive = { version = "0.1.0", path = "../zerocbor_derive", optional = true }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
ciborium = "0.2"
cbor4ii = { version = "1.2", features = ["serde1", "use_std"] }
minicbor = { version = "2", features = ["alloc", "derive"] }
zerocbor_derive = { path = "../zerocbor_derive" }
