[package]
name = "zerocbor_derive"
description = "proc-macro crate for zerocbor"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/zerocbor_derive"
keywords = ["cbor", "derive", "macros", "no-std", "serialization"]
categories = ["development-tools::procedural-macro-helpers", "encoding"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
zerocbor = { path = "../zerocbor", features = ["derive"] }
