[package]
name = "zerocbor_derive"
description = "proc-macro crate for zerocbor"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/nuskey8/zerocbor"
documentation = "https://docs.rs/zerocbor_derive"
keywords = ["cbor", "derive", "macros", "no-std", "serialization"]
categories = ["development-tools::procedural-macro-helpers", "encoding"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
zerocbor = { path = "../zerocbor", features = ["derive"] }
